# -*- coding: utf-8 -*-
"""all_Face.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T1xQs0ppuMAwtNkYXMtmIEHuaVC3-ajZ
"""

!pip install face_recognition

# --- 1. INSTALL DEPENDENCIES ---

import face_recognition
import numpy as np
import cv2
from IPython.display import display, Javascript
from google.colab.output import eval_js
from base64 import b64decode
from google.colab.patches import cv2_imshow

print("Setup complete. Loading JS camera...")

# --- 2. JAVASCRIPT WEBCAM CAPTURE SNIPPET ---
# --- JAVASCRIPT WEBCAM CAPTURE - LOGITECH FIX ---
 # --- JAVASCRIPT WEBCAM CAPTURE - LOGITECH / NO PREVIEW FIX ---
def take_photo(filename='photo.jpg', quality=0.8):
  js = Javascript('''
    async function takePhoto(quality) {
      const div = document.createElement('div');
      const capture = document.createElement('button');
      capture.textContent = 'Capture (Wait 2s before clicking...)';

      // Make the capture button large so it's obvious to click
      capture.style.padding = '10px 20px';
      capture.style.fontSize = '16px';
      capture.style.marginBottom = '10px';
      div.appendChild(capture);

      const video = document.createElement('video');
      // HARDCODE the styling to ensure the preview is visible
      video.style.display = 'block';
      video.style.maxWidth = '640px';
      video.style.width = '100%';
      video.autoplay = true;
      video.playsInline = true;

      const stream = await navigator.mediaDevices.getUserMedia({video: true});

      document.body.appendChild(div);
      div.appendChild(video);
      video.srcObject = stream;
      await video.play();

      google.colab.output.setIframeHeight(document.documentElement.scrollHeight, true);

      // Give Logitech cameras 2 seconds to initialize their pixel buffer
      await new Promise(resolve => setTimeout(resolve, 2000));

      // Wait for Capture button to be clicked.
      await new Promise((resolve) => capture.onclick = resolve);

      const canvas = document.createElement('canvas');
      canvas.width = video.videoWidth;
      canvas.height = video.videoHeight;
      canvas.getContext('2d').drawImage(video, 0, 0);

      // Release camera
      stream.getVideoTracks()[0].stop();
      div.remove();
      return canvas.toDataURL('image/jpeg', quality);
    }
    ''')
  from IPython.display import display
  display(js)
  from google.colab.output import eval_js
  data = eval_js('takePhoto({})'.format(quality))
  from base64 import b64decode
  binary = b64decode(data.split(',')[1])
  with open(filename, 'wb') as f:
    f.write(binary)
  return filename


# --- 3. FIX KNOWN FACES ---
# NOTE: You MUST upload an image (e.g., 'elon.jpg') into the Colab file explorer first!
try:
    # --- REPLACE THESE TWO LINES WITH YOUR ACTUAL FILE AND NAME ---
    known_image = face_recognition.load_image_file("/content/facrTracker/myPic.JPG")
    known_name = "Saikat Sengupta"

    known_encoding = face_recognition.face_encodings(known_image)[0]
except FileNotFoundError:
    print("\n[ERROR] KNOWN FACE IMAGE NOT FOUND!")
    print("Did you remember to upload the image into the Colab file explorer (Left sidebar -> Folder icon)?")
    import sys
    sys.exit(1)


# --- 4. CAPTURE WEBCAM ---
image_path = None # Initialize image_path to None
try:
  print("\nSmile! Looking for webcam...")
  print("Click the 'Capture' button below the cell to take a photo.")
  captured_path = take_photo('live_capture.jpg')
  if captured_path: # Only update image_path if a path was successfully returned
    image_path = captured_path
except Exception as err:
  print(str(err))
  print("\n[ERROR] Failed to capture image from webcam. Face recognition will be skipped.")

# --- 5. FACE RECOGNITION AND DISPLAY ---
if image_path: # This condition now correctly checks if a valid image path exists
    print("\nAnalyzing face...")
    frame = cv2.imread(image_path)
    if frame is None: # Add a check to ensure the image was loaded successfully
        print(f"\n[ERROR] Could not load image from {image_path}. Skipping face recognition.")
    else:
        rgb_frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)

        face_locations = face_recognition.face_locations(rgb_frame)
        face_encodings = face_recognition.face_encodings(rgb_frame, face_locations)

        for (top, right, bottom, left), face_encoding in zip(face_locations, face_encodings):
            matches = face_recognition.compare_faces([known_encoding], face_encoding)
            name = "Unknown"

            if matches[0]:
                name = known_name

            if name == "Unknown":
                color = (0, 0, 255) # Red for unknown
            else:
                color = (0, 255, 0) # Green for recognized

            cv2.rectangle(frame, (left, top), (right, bottom), color, 2)
            cv2.rectangle(frame, (left, bottom - 35), (right, bottom), color, cv2.FILLED)
            font = cv2.FONT_HERSHEY_DUPLEX
            cv2.putText(frame, name, (left + 6, bottom - 6), font, 1.0, (255, 255, 255), 1)

        print("\nResult:")
        cv2_imshow(frame)
else:
    print("\nSkipping face recognition as no image was captured.")

# Note: In a Google Colab Notebook, you can paste this ENTIRE file into a single code cell.
# The `!pip` command at the top will run safely in Colab as a shell command.

!pip install face_recognition

import face_recognition
import numpy as np
import cv2
from IPython.display import display, Javascript
from google.colab.output import eval_js
from base64 import b64decode
from google.colab.patches import cv2_imshow

print("Setup complete. Loading JS camera...")

# --- 1. JAVASCRIPT WEBCAM CAPTURE SNIPPET ---
def take_photo(filename='photo.jpg', quality=0.8):
  js = Javascript('''
    async function takePhoto(quality) {
      const div = document.createElement('div');
      const capture = document.createElement('button');
      capture.textContent = 'Capture (Wait 2s before clicking...)';

      // Make the button large so it's obvious
      capture.style.padding = '10px 20px';
      capture.style.fontSize = '16px';
      capture.style.marginBottom = '10px';
      div.appendChild(capture);

      const video = document.createElement('video');
      // HARDCODE the styling to ensure the preview is visible
      video.style.display = 'block';
      video.style.maxWidth = '640px';
      video.style.width = '100%';
      video.autoplay = true;
      video.playsInline = true;

      const stream = await navigator.mediaDevices.getUserMedia({video: true});

      document.body.appendChild(div);
      div.appendChild(video);
      video.srcObject = stream;
      await video.play();

      google.colab.output.setIframeHeight(document.documentElement.scrollHeight, true);

      // Give Logitech cameras 2 seconds to initialize their pixel buffer
      await new Promise(resolve => setTimeout(resolve, 2000));

      await new Promise((resolve) => capture.onclick = resolve);

      const canvas = document.createElement('canvas');
      canvas.width = video.videoWidth;
      canvas.height = video.videoHeight;
      canvas.getContext('2d').drawImage(video, 0, 0);
      stream.getVideoTracks()[0].stop();
      div.remove();
      return canvas.toDataURL('image/jpeg', quality);
    }
    ''')
  display(js)
  data = eval_js('takePhoto({})'.format(quality))
  binary = b64decode(data.split(',')[1])
  with open(filename, 'wb') as f:
    f.write(binary)
  return filename

# --- 2. LOAD KNOWN FACES ---
import os
import sys

# Create a folder in Colab to hold the images if it doesn't exist
KNOWN_FACES_DIR = "known_faces"
if not os.path.exists(KNOWN_FACES_DIR):
    os.makedirs(KNOWN_FACES_DIR)
    print(f"[*] I just created a folder named '{KNOWN_FACES_DIR}' on the left sidebar.")
    print("[!] Please upload your face images into that folder.")
    print("[!] Make sure to rename them to the person's name (e.g., 'Elon Musk.jpg').")
    print("[*] Re-run this cell after uploading!")
    sys.exit(0)

known_encodings = []
known_names = []

print(f"[*] Scanning '{KNOWN_FACES_DIR}' for faces...")
# Loop through all files in the known_faces folder
for filename in os.listdir(KNOWN_FACES_DIR):
    if filename.endswith(".jpg") or filename.endswith(".png") or filename.endswith(".jpeg"):
        # The name of the file becomes the person's name
        name = os.path.splitext(filename)[0]
        img_path = os.path.join(KNOWN_FACES_DIR, filename)

        try:
            image = face_recognition.load_image_file(img_path)
            # Make sure at least one face is found in the image
            encodings = face_recognition.face_encodings(image)
            if len(encodings) > 0:
                known_encodings.append(encodings[0])
                known_names.append(name)
                print(f"  -> Successfully Loaded: {name}")
            else:
                print(f"  [Warning] No face found in {filename}")
        except Exception as e:
            print(f"  [Error] Could not load {filename}: {str(e)}")

# Stop if no faces were added
if len(known_encodings) == 0:
    print("\n[ERROR] No valid faces were found in the folder!")
    print("Please upload some images first.")
    sys.exit(1)


# --- 3. CAPTURE WEBCAM ---
try:
  print("\nSmile! Looking for webcam...")
  print("Click the 'Capture' button below the cell to take a photo.")
  image_path = take_photo('live_capture.jpg')
except Exception as err:
  print(str(err))

# --- 4. FACE RECOGNITION AND DISPLAY ---
print("\nAnalyzing face...")
frame = cv2.imread(image_path)
rgb_frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)

face_locations = face_recognition.face_locations(rgb_frame)
face_encodings = face_recognition.face_encodings(rgb_frame, face_locations)

for (top, right, bottom, left), face_encoding in zip(face_locations, face_encodings):
    name = "Unknown"

    # Compare against ALL known faces in the database
    matches = face_recognition.compare_faces(known_encodings, face_encoding)
    face_distances = face_recognition.face_distance(known_encodings, face_encoding)

    if len(face_distances) > 0:
        # Find exactly which person it matches the closest
        best_match_index = np.argmin(face_distances)
        if matches[best_match_index]:
            name = known_names[best_match_index]

    if name == "Unknown":
        color = (0, 0, 255) # Red for unknown
    else:
        color = (0, 255, 0) # Green for recognized

    cv2.rectangle(frame, (left, top), (right, bottom), color, 2)
    cv2.rectangle(frame, (left, bottom - 35), (right, bottom), color, cv2.FILLED)
    font = cv2.FONT_HERSHEY_DUPLEX
    cv2.putText(frame, name, (left + 6, bottom - 6), font, 1.0, (255, 255, 255), 1)

print("\nResult:")
cv2_imshow(frame)